name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Go 1.13
        uses: actions/setup-go@v4
        with:
          go-version: 1.13.x

      - name: build game
        run: |
          git clone github.com/tmedwards/tweego
          cd tweego
          git checkout master
          go get
          go install
          tweego 'CS 2990 Narrative.twee' -o dist/index.html

      - name: Deploy to Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./dist